
try{
    let a="vaishnavi"
    console.log(a.length)
    console.log("hi from inside")
    }
catch(err){
    console.log("From catch statements")
}   